// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VBBSManager.Infrastructure.Persistence;

#nullable disable

namespace VBBSManager.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("VBBSManager.Domain.Entities.MetaCampaignDailyInsight", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<string>("CampaignId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("CampaignName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<long>("Impressions").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Clicks").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Reach").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<decimal>("Spend").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<decimal?>("Cpc").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Cpm").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Ctr").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<decimal?>("Frequency").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<int>("Conversions").HasColumnType("integer").HasDefaultValue(0);
            b.Property<decimal>("Revenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "CampaignId", "Date").IsUnique();
            b.HasIndex("TenantId", "Date");
            b.ToTable("MetaCampaignDailyInsights");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.MetaAdSetDailyInsight", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<string>("CampaignId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("CampaignName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("AdSetId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("AdSetName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<long>("Impressions").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Clicks").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Reach").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<decimal>("Spend").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<decimal?>("Cpc").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Cpm").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Ctr").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<decimal?>("Frequency").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<int>("Conversions").HasColumnType("integer").HasDefaultValue(0);
            b.Property<decimal>("Revenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "AdSetId", "Date").IsUnique();
            b.HasIndex("TenantId", "Date");
            b.ToTable("MetaAdSetDailyInsights");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.MetaAdDailyInsight", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<string>("CampaignId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("CampaignName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("AdSetId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("AdSetName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("AdId").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
            b.Property<string>("AdName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<long>("Impressions").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Clicks").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("Reach").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<decimal>("Spend").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<decimal?>("Cpc").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Cpm").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<decimal?>("Ctr").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<decimal?>("Frequency").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<int>("Conversions").HasColumnType("integer").HasDefaultValue(0);
            b.Property<decimal>("Revenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "AdId", "Date").IsUnique();
            b.HasIndex("TenantId", "Date");
            b.ToTable("MetaAdDailyInsights");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.DailyAdSpendSummary", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<decimal>("TotalSpend").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<long>("TotalImpressions").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<long>("TotalClicks").HasColumnType("bigint").HasDefaultValue(0L);
            b.Property<int>("TotalConversions").HasColumnType("integer").HasDefaultValue(0);
            b.Property<decimal>("TotalRevenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)").HasDefaultValue(0m);
            b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Date").IsUnique();
            b.ToTable("DailyAdSpendSummaries");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.DailySalesSummary", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateOnly>("Date").HasColumnType("date");
            b.Property<decimal>("GrossRevenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("HotmartFeeAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<DateTime>("LastSyncedAt").HasColumnType("timestamp with time zone");
            b.Property<decimal>("NetRevenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<int>("TotalSales").HasColumnType("integer");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Date").IsUnique();
            b.ToTable("DailySalesSummaries");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.Alert", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsRead").HasColumnType("boolean");
            b.Property<bool>("IsResolved").HasColumnType("boolean");
            b.Property<string>("Message").IsRequired().HasColumnType("text");
            b.Property<string>("Metadata").HasColumnType("text");
            b.Property<DateTime?>("ResolvedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Severity").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("Title").IsRequired().HasColumnType("text");
            b.Property<int>("Type").HasColumnType("integer");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("Alerts");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.FinancialConfig", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<decimal>("AccountingCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<decimal>("FederalTaxPercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<decimal>("HotmartFeePercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<decimal>("HotmartFixedFeePerTransaction").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
            b.Property<decimal>("HotmartPlayerCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("InstallmentFeePercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<decimal>("InstallmentSalesPercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<decimal>("InvoicingCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("ManychatCost").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("MetaAdsTaxPercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<decimal>("MonthlyGrossRevenue").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("MonthlyAdSpend").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
            b.Property<decimal>("RefundRatePercent").HasPrecision(5, 4).HasColumnType("numeric(5,4)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId").IsUnique();
            b.ToTable("FinancialConfigs");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.Integration", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("CredentialsEncrypted").IsRequired().HasColumnType("text");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<DateTime?>("LastSyncAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Provider").HasColumnType("integer");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("Integrations");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.PlanningGoal", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("ActionIfFailed").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("Category").IsRequired().HasColumnType("text");
            b.Property<string>("ComparisonType").IsRequired().HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<decimal?>("CurrentValue").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<int>("SortOrder").HasColumnType("integer");
            b.Property<decimal>("TargetValue").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("Unit").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("TenantId");
            b.HasIndex("TenantId", "Key").IsUnique();
            b.ToTable("PlanningGoals");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.RefreshToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.Property<string>("Token").IsRequired().HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("RefreshTokens");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.Property<string>("Slug").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("Tenants");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<Guid>("TenantId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Email").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.RefreshToken", b =>
        {
            b.HasOne("VBBSManager.Domain.Entities.User", "User")
                .WithMany("RefreshTokens")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.User", b =>
        {
            b.HasOne("VBBSManager.Domain.Entities.Tenant", "Tenant")
                .WithMany("Users")
                .HasForeignKey("TenantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Tenant");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.Tenant", b =>
        {
            b.Navigation("Users");
        });

        modelBuilder.Entity("VBBSManager.Domain.Entities.User", b =>
        {
            b.Navigation("RefreshTokens");
        });
#pragma warning restore 612, 618
    }
}
